development:
  adapter: postgresql
  user: tmb
  password:
  encoding: unicode
  database: db/pantry_development

test: &test
  adapter: postgresql
  user: tmb
  password: 
  encoding: unicode
  database: db/pantry_test

production:
  adapter: postgresql
  user: pantry
  password: tmb8518 
  encoding: unicode
  database: db/pantry_production

cucumber:
  <<: *test
