# original version autogenerated by Stepford: https://github.com/garysweaver/stepford

FactoryGirl.define do
  
  factory :admin_user do
    sequence(:id)
    sequence(:email) do |n|; "person#{n}@example.com"; end
    encrypted_password ''
  end
  
  factory :donation do
    sequence(:id)
  end
  
  factory :donor do
    sequence(:id)
  end
  
  factory :household do
    sequence(:id)
  end
  
  factory :neighbor do
    sequence(:id)
  end
  
  factory :time_card do
    sequence(:id)
  end
  
  factory :user do
    sequence(:id)
    sequence(:email) do |n|; "person#{n}@example.com"; end
    encrypted_password ''
  end
  
  factory :visit do
    sequence(:id)
    visited_on { 2.weeks.ago }
  end
  
  factory :volunteer do
    sequence(:id)
  end
  
end
